### ISSUE TITLE
AttributeError: 'module' object has no attribute 'set_blocking'

### ISSUE THREAD

**Issue by Schalli1987** [sshuttle/sshuttle#486]
Hi there,

I was using sshuttle 0.78.5 without any issues, when upgrading to 1.0.[0-3] I keep getting the following error:

> /run -r remoteHost --dns 10.12.0.0/16 10.10.4.0/24
> [local sudo] Password: 
> client: Connected.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "assembler.py", line 41, in <module>
>   File "sshuttle.server", line 395, in main
>   File "sshuttle.ssnet", line 600, in runonce
>   File "sshuttle.ssnet", line 490, in callback
>   File "sshuttle.ssnet", line 439, in flush
> AttributeError: 'module' object has no attribute 'set_blocking'
> client: fatal: server died with error code 1

I'm running on arch linux (5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64 GNU/Linux) using Python 3.8.3

**Comment by brianmay** [comment]
This is because the version of Python you have is too old. You need at least Python 3.5 now.

**Comment by Schalli1987** [comment]
As I wrote at the bottom of my report, I'm usign Python 3.8.3, which I think is greater than 3.5 isn't it?

**Comment by brianmay** [comment]
What version of Python do you have on the server?

**Comment by Schalli1987** [comment]
Ah, on the server it's indeed 2.7.9, didn't suspect that this could be am issue
