### ISSUE TITLE
Import error/String mismatch on version 1.0.1 (MacOS)

### ISSUE THREAD

**Issue by darakian** [sshuttle/sshuttle#457]
I just updated to 1.0.1 and I'm seeing 
```
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (66 bytes)
server: assembling u'sshuttle.helpers' (902 bytes)
server: assembling u'sshuttle.ssnet' (5734 bytes)
server: assembling u'sshuttle.hostwatch' (2463 bytes)
server: assembling u'sshuttle.server' (3673 bytes)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 25, in <module>
  File "sshuttle.server", line 9, in <module>
ImportError: cannot import name which
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

This obviously is a problem as I can't use sshuttle at all. My usage is of the form
```
sudo sshuttle -vvv -vr user@box.mydomain.com CIDR/RANGE
```
This is sshing into an openssh server on the remote end which was working on version `0.78.5_2`.

**Comment by IronicBadger** [comment]
Can confirm same issue. I'd post my output but it's identical.

**Comment by lantrix** [comment]
> Can confirm same issue. I'd post my output but it's identical. How does one pick a specific version with brew?

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/eed4935aa1d8c7ff3b7e63c8063249c6c046677e/Formula/sshuttle.rb
```

**Comment by itchyny** [comment]
Following steps work for me to downgrade the sshuttle version.
```sh
homebrew_core_dir=$(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core
git -C "$homebrew_core_dir" checkout 34ef288f5b2e9f092c73018de593bb4dee2c01a8 "$homebrew_core_dir/Formula/sshuttle.rb"
brew reinstall sshuttle
brew pin sshuttle
git -C "$homebrew_core_dir" checkout HEAD "$homebrew_core_dir/Formula/sshuttle.rb"
```

**Comment by brianmay** [comment]
itchyny <notifications@github.com> writes:

> Following steps work for me to downgrade the sshuttle version.

It is a concern if the latest sshuttle is not working correctly, but
unfortunately the error quoted does nothing to help diagnose the
problem. All the error says is "something went wrong trying to start the
remote process".

Unfortunately I don't have time to try to troubleshoot this, somebody
else will have to do that.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by itchyny** [comment]
The version of Python on my ssh host is 2.4.3 which makes import shutil fail. I think I'll contact to our infra team.

**Comment by itchyny** [comment]
The version of Python on my ssh host is 2.4.3 which makes import shutil fail. I use 3.7.7 on my local machine but can't update the version on the ssh host. I think sshuttle was updated assuming Python 3 in the server program so I'll contact to our infra team.

**Comment by darakian** [comment]
@brianmay To be clear. Is the fix here is to install python 3 on my ssh server?

**Comment by brianmay** [comment]
Jon Moroney <notifications@github.com> writes:

> @brianmay To be clear. Is the fix here is to install python 3 on my ssh server?

I believe so.

Note however that the error could be caused by a number of different
reasons. The wrong Python version is just one possible cause.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by darakian** [comment]
Ok. I've installed python3 on my server and everything is working with sshuttle 1.0.1. Thanks for the feedback and for making sshuttle :)
